targets:
    $default:
      builders:
        reflectable:
          generate_for:
            - lib/main.dart
            - lib/persistence/core/annotations/*
            - lib/service/doamin/*
          options:
            formatted: true
