import 'package:flutter_base_project/persistence/core/information/entity_information.dart';
import 'package:flutter_base_project/persistence/reflector/reflector.dart';
import 'package:reflectable/reflectable.dart';

class FirebaseEntityInformation<E> extends EntityInformation<E> {
  FirebaseEntityInformation(
      {ClassMirror entityClass,
      String idField,
      bool idIsAutoGenerated,
      String entityName,
      List<String> columns})
      : super(
            entityClass: entityClass,
            idField: idField,
            idIsAutoGenerated: idIsAutoGenerated,
            entityName: entityName,
            columns: columns);

  @override
  E fromJson<E>(String jsonStr) {
    return null;
  }

  @override
  String toJson<E>(E entity) {
    InstanceMirror entityInstance = reflector.reflect(entity);
    Object idValue = entityInstance.invokeGetter(this.idField);

    String json = "{";
    if (idValue != null) {
      json += "\"$idValue\": {";
    }

    columns.forEach((columnName) {
      Object columnValue = entityInstance.invokeGetter(columnName);
      json += "\"$columnName\" : \"" + columnValue.toString() + "\"";
      if (columns.last != columnName) {
        json += ",";
      }
    });

    if (idValue != null) {
      json += "}";
    }
    json += "}";
    return json;
  }
}
