import 'package:flutter_base_project/persistence/core/providers/entity_information_provider.dart';
import 'package:flutter_base_project/persistence/firebase/information/firebase_entity_information.dart';
import 'package:flutter_base_project/persistence/firebase/resolvers/firebase_entity_resolver.dart';
import 'package:flutter_base_project/persistence/reflector/reflector.dart';
import 'package:reflectable/reflectable.dart';

class FirebaseEntityInformationProvider
    extends EntityInformationProvider<FirebaseEntityInformation> {
  FirebaseEntityResolver firebaseEntityResolver =
      FirebaseEntityResolver.newInstance();

  @override
  FirebaseEntityInformation newInstance<T>() {
    ClassMirror entityClass = reflector.reflectType(T);
    return FirebaseEntityInformation<T>(
        entityClass: entityClass,
        idField: firebaseEntityResolver.idField(entityClass),
        idIsAutoGenerated:
            firebaseEntityResolver.idIsAutoGenerated(entityClass),
        entityName: firebaseEntityResolver.name(entityClass),
        columns: firebaseEntityResolver.columns(entityClass));
  }
}
