// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:flutter_base_project/persistence/annotations/column.dart'
    as prefix3;
import 'package:flutter_base_project/persistence/annotations/entity.dart'
    as prefix4;
import 'package:flutter_base_project/persistence/annotations/id.dart'
    as prefix2;
import 'package:flutter_base_project/persistence/reflector/reflector.dart'
    as prefix0;
import 'package:flutter_base_project/service/domain/user.dart' as prefix1;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.Reflector(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'User',
            r'.User',
            7,
            0,
            const prefix0.Reflector(),
            const <int>[0, 1, 5, 10],
            const <int>[11, 5, 12, 13, 14, 6, 7, 8, 9],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (b) =>
                  ({id, name}) => b ? prefix1.User(id: id, name: name) : null
            },
            0,
            0,
            const <int>[],
            const <Object>[
              prefix0.reflector,
              const prefix4.Entity(name: "user")
            ],
            null),
        r.NonGenericClassMirrorImpl(
            r'Id',
            r'.Id',
            7,
            1,
            const prefix0.Reflector(),
            const <int>[2, 16],
            const <int>[11, 17, 12, 13, 14, 15],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (b) => ({autoGenerated = false}) =>
                  b ? prefix2.Id(autoGenerated: autoGenerated) : null
            },
            1,
            1,
            const <int>[],
            const <Object>[prefix0.reflector],
            null),
        r.NonGenericClassMirrorImpl(
            r'Column',
            r'.Column',
            7,
            2,
            const prefix0.Reflector(),
            const <int>[3, 19],
            const <int>[11, 17, 12, 13, 14, 18],
            const <int>[],
            -1,
            {},
            {},
            {r'': (b) => ({name}) => b ? prefix3.Column(name: name) : null},
            2,
            2,
            const <int>[],
            const <Object>[prefix0.reflector],
            null),
        r.NonGenericClassMirrorImpl(
            r'Entity',
            r'.Entity',
            7,
            3,
            const prefix0.Reflector(),
            const <int>[4, 21],
            const <int>[11, 17, 12, 13, 14, 20],
            const <int>[],
            -1,
            {},
            {},
            {r'': (b) => ({name}) => b ? prefix4.Entity(name: name) : null},
            3,
            3,
            const <int>[],
            const <Object>[prefix0.reflector],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(
            r'id',
            32773,
            0,
            const prefix0.Reflector(),
            -1,
            4,
            4,
            const <int>[],
            const <Object>[const prefix2.Id(autoGenerated: true)]),
        r.VariableMirrorImpl(
            r'name',
            32773,
            0,
            const prefix0.Reflector(),
            -1,
            4,
            4,
            const <int>[],
            const <Object>[const prefix3.Column(name: "name")]),
        r.VariableMirrorImpl(r'autoGenerated', 33797, 1,
            const prefix0.Reflector(), -1, 5, 5, const <int>[], const []),
        r.VariableMirrorImpl(r'name', 33797, 2, const prefix0.Reflector(), -1,
            4, 4, const <int>[], const []),
        r.VariableMirrorImpl(r'name', 33797, 3, const prefix0.Reflector(), -1,
            4, 4, const <int>[], const []),
        r.MethodMirrorImpl(r'toString', 131074, 0, -1, 4, 4, const <int>[],
            const <int>[], const prefix0.Reflector(), const <Object>[override]),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 0, 6),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 0, 7),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 1, 8),
        r.ImplicitSetterMirrorImpl(const prefix0.Reflector(), 1, 9),
        r.MethodMirrorImpl(r'', 0, 0, -1, 0, 0, const <int>[],
            const <int>[0, 1], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'==', 131074, null, -1, 5, 5, const <int>[],
            const <int>[4], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'noSuchMethod', 65538, null, null, null, null,
            const <int>[], const <int>[5], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'hashCode', 131075, null, -1, 6, 6, const <int>[],
            const <int>[], const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'runtimeType', 131075, null, -1, 7, 7,
            const <int>[], const <int>[], const prefix0.Reflector(), const []),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 2, 15),
        r.MethodMirrorImpl(r'', 128, 1, -1, 1, 1, const <int>[], const <int>[6],
            const prefix0.Reflector(), const []),
        r.MethodMirrorImpl(r'toString', 131074, null, -1, 4, 4, const <int>[],
            const <int>[], const prefix0.Reflector(), const []),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 3, 18),
        r.MethodMirrorImpl(r'', 128, 2, -1, 2, 2, const <int>[], const <int>[7],
            const prefix0.Reflector(), const []),
        r.ImplicitGetterMirrorImpl(const prefix0.Reflector(), 4, 20),
        r.MethodMirrorImpl(r'', 128, 3, -1, 3, 3, const <int>[], const <int>[8],
            const prefix0.Reflector(), const [])
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(r'id', 45062, 10, const prefix0.Reflector(), -1,
            4, 4, const <int>[], const [], null, #id),
        r.ParameterMirrorImpl(r'name', 45062, 10, const prefix0.Reflector(), -1,
            4, 4, const <int>[], const [], null, #name),
        r.ParameterMirrorImpl(r'_id', 32870, 7, const prefix0.Reflector(), -1,
            4, 4, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(r'_name', 32870, 9, const prefix0.Reflector(), -1,
            4, 4, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(r'other', 32774, 11, const prefix0.Reflector(),
            -1, 8, 8, const <int>[], const [], null, null),
        r.ParameterMirrorImpl(
            r'invocation',
            32774,
            12,
            const prefix0.Reflector(),
            -1,
            9,
            9,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'autoGenerated',
            47110,
            16,
            const prefix0.Reflector(),
            -1,
            5,
            5,
            const <int>[],
            const [],
            false,
            #autoGenerated),
        r.ParameterMirrorImpl(r'name', 45062, 19, const prefix0.Reflector(), -1,
            4, 4, const <int>[], const [], null, #name),
        r.ParameterMirrorImpl(r'name', 45062, 21, const prefix0.Reflector(), -1,
            4, 4, const <int>[], const [], null, #name)
      ],
      <Type>[
        prefix1.User,
        prefix2.Id,
        prefix3.Column,
        prefix4.Entity,
        String,
        bool,
        int,
        Type,
        Object,
        Invocation
      ],
      4,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'id': (dynamic instance) => instance.id,
        r'name': (dynamic instance) => instance.name,
        r'autoGenerated': (dynamic instance) => instance.autoGenerated
      },
      {
        r'id=': (dynamic instance, value) => instance.id = value,
        r'name=': (dynamic instance, value) => instance.name = value
      },
      <m.LibraryMirror>[
        r.LibraryMirrorImpl(r'', Uri.parse(r'reflectable://0/'),
            const prefix0.Reflector(), const <int>[], {}, {}, const [], null),
        r.LibraryMirrorImpl(r'', Uri.parse(r'reflectable://1/'),
            const prefix0.Reflector(), const <int>[], {}, {}, const [], null),
        r.LibraryMirrorImpl(r'', Uri.parse(r'reflectable://2/'),
            const prefix0.Reflector(), const <int>[], {}, {}, const [], null),
        r.LibraryMirrorImpl(r'', Uri.parse(r'reflectable://3/'),
            const prefix0.Reflector(), const <int>[], {}, {}, const [], null)
      ],
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
