import 'package:flutter_base_project/persistence/core/annotations/column.dart';
import 'package:flutter_base_project/persistence/core/annotations/entity.dart';
import 'package:flutter_base_project/persistence/core/annotations/id.dart';
import 'package:flutter_base_project/persistence/reflector/reflector.dart';

@reflector
@Entity(name: "user", schema: "teste")
class User {
  @Id(autoGenerated: true)
  String id;
  @Column(name: "name")
  String name;

  User({this.id, this.name});

  @override
  String toString() {
    return """
    User: {
      id: $id,
      name: $name
    }
    """;
  }
}
